const SUPABASE_URL='https://ujddnzckfrksetsfgden.supabase.co';
const SUPABASE_KEY='sb_publishable_Lo9uaX-E9hHcL-w2El6M3g_OoCRma3W';
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const animals=[['01','Avestruz','🦤'],['02','Águia','🦅'],['03','Burro','🫏'],['04','Borboleta','🦋'],['05','Cachorro','🐶'],['06','Cabra','🐐'],['07','Carneiro','🐏'],['08','Camelo','🐪'],['09','Cobra','🐍'],['10','Coelho','🐇'],['11','Cavalo','🐎'],['12','Elefante','🐘'],['13','Galo','🐓'],['14','Gato','🐱'],['15','Jacaré','🐊'],['16','Leão','🦁'],['17','Macaco','🐒'],['18','Porco','🐷'],['19','Pavão','🦚'],['20','Peru','🦃'],['21','Touro','🐂'],['22','Tigre','🐯'],['23','Urso','🐻'],['24','Veado','🦌'],['25','Vaca','🐄']];
let user=null,draw=null,selected=new Set();
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function msg(t,e=false){$('message').textContent=t;$('message').className=`message ${e?'error':''}`}
function renderGrid(){ $('animalGrid').innerHTML=animals.map(([n,name,emoji])=>`<button type="button" class="animal-card ${selected.has(Number(n))?'selected':''}" data-n="${n}"><span class="animal-number">${n}</span><span class="animal-emoji">${emoji}</span><span class="animal-name">${name}</span></button>`).join(''); document.querySelectorAll('.animal-card').forEach(b=>b.onclick=()=>{const n=Number(b.dataset.n);selected.has(n)?selected.delete(n):selected.add(n);renderGrid();renderSelected()}); }
function renderSelected(){ $('selectedList').innerHTML=[...selected].sort((a,b)=>a-b).map(n=>{const a=animals[n-1];return `<span class="selected-pill">${a[2]} ${a[0]} · ${a[1]}</span>`}).join(''); $('participateBtn').disabled=!user||!draw||selected.size===0; }
async function load(){const {data:{user:u}}=await sb.auth.getUser();user=u;if(!user){msg('Entre na sua conta para participar.',true);$('participateBtn').disabled=true;return}
const {data,error}=await sb.from('animal_sorteios').select('id,nome,descricao,concurso,data_sorteio,status,resultado_numero,resultado_animal').eq('status','ativo').order('data_sorteio',{ascending:true}).limit(1).maybeSingle();
if(error||!data){$('drawInfo').innerHTML='<div class="empty">Nenhum sorteio ativo no momento.</div>';return} draw=data;$('drawInfo').innerHTML=`<div class="card"><h2>${esc(data.nome)}</h2><p>${esc(data.descricao||'')}</p><p><strong>Concurso:</strong> ${data.concurso} · <strong>Sorteio:</strong> ${new Date(data.data_sorteio+'T00:00:00').toLocaleDateString('pt-BR')}</p></div>`;renderGrid();renderSelected();loadHistory();}
async function participate(){if(!draw||!user||!selected.size)return; const rows=[...selected].map(n=>({sorteio_id:draw.id,comprador_id:user.id,animal_numero:n,animal_nome:animals[n-1][1]}));const {error}=await sb.from('animal_participacoes').insert(rows);if(error){msg(error.code==='23505'?'Você já participa com um ou mais desses animais.':error.message,true);return}msg('Participação registrada com sucesso.');selected.clear();renderGrid();renderSelected();loadHistory();}
async function loadHistory(){const {data,error}=await sb.from('animal_participacoes').select('id,animal_numero,animal_nome,created_at,sorteio_id,animal_sorteios(nome,concurso,data_sorteio,status,resultado_numero,resultado_animal)').eq('comprador_id',user.id).order('created_at',{ascending:false});if(error){$('history').innerHTML=`<div class="empty">${esc(error.message)}</div>`;return}if(!data?.length){$('history').innerHTML='<div class="empty">Você ainda não possui participações.</div>';return}const groups={};data.forEach(x=>(groups[x.sorteio_id]??=[]).push(x));$('history').innerHTML=Object.values(groups).map(items=>{const d=items[0].animal_sorteios;return `<article class="card" style="margin-bottom:12px"><strong>${esc(d?.nome||'Sorteio')}</strong><p>Concurso ${esc(d?.concurso||'')} · ${new Date(d.data_sorteio+'T00:00:00').toLocaleDateString('pt-BR')}</p><p>${items.map(x=>`${animals[x.animal_numero-1]?.[2]||'🐾'} ${x.animal_numero} · ${esc(x.animal_nome)}`).join(' · ')}</p>${d?.resultado_numero?`<p><strong>Resultado:</strong> ${d.resultado_numero} · ${esc(d.resultado_animal||'')}</p>`:''}</article>`}).join('')}
$('participateBtn').onclick=participate;load();